[package]
name = "multi-party-schnorr"
version = "0.1.0"
authors = [
    "Omer <omer@kzencorp.com>",
    "Gary <gary@kzencorp.com>"
]

[lib]
crate-type = ["lib"]

[dependencies]
cryptography-utils = { git = "https://github.com/KZen-networks/cryptography-utils" ,  features =  ["curvesecp256k1"]}


[dev-dependencies]
hex = "0.3.2"
